// GENERATED by tool/generate_api.dart from tool/openapi.json
// (Slopcafe API contract 2.2.0). DO NOT EDIT BY HAND.
// Re-run `dart run tool/generate_api.dart && dart run build_runner build`
// after re-pinning the spec. See GEMINI.md.

/// Canonical Slopcafe API error codes — the discriminants of the
/// `ErrorBody` oneOf union (the `error` field). Parse a wire value
/// with [ErrorCode.fromWire]; unknown/forward-compat codes resolve to
/// [ErrorCode.unknown]. See lib/api/api_error.dart for envelope parsing.
enum ErrorCode {
  badCursor('bad_cursor'),
  badIntegrityHeader('bad_integrity_header'),
  badJson('bad_json'),
  badLimit('bad_limit'),
  badQuery('bad_query'),
  badRequest('bad_request'),
  badSlug('bad_slug'),
  badStatus('bad_status'),
  badTarget('bad_target'),
  clientExists('client_exists'),
  csrfFailed('csrf_failed'),
  emptyBody('empty_body'),
  gone('gone'),
  integrityMismatch('integrity_mismatch'),
  internal('internal'),
  invalidSlug('invalid_slug'),
  invalidStatus('invalid_status'),
  invalidVisibility('invalid_visibility'),
  misconfigured('misconfigured'),
  notFound('not_found'),
  preconditionFailed('precondition_failed'),
  preconditionRequired('precondition_required'),
  slugLocked('slug_locked'),
  slugRedirected('slug_redirected'),
  slugRetired('slug_retired'),
  slugTaken('slug_taken'),
  sourceUnavailable('source_unavailable'),
  storageCapExceeded('storage_cap_exceeded'),
  tooDeep('too_deep'),
  tooLarge('too_large'),
  unauthorized('unauthorized'),
  unsupportedMediaType('unsupported_media_type'),
  versionNotFound('version_not_found'),

  /// Not part of the contract — a code this build does not recognise.
  unknown('');

  const ErrorCode(this.wire);

  /// The on-the-wire string sent by the backend.
  final String wire;

  /// Resolve a wire string to a code, falling back to [unknown].
  static ErrorCode fromWire(String? wire) {
    if (wire == null) return ErrorCode.unknown;
    for (final c in ErrorCode.values) {
      if (c.wire == wire) return c;
    }
    return ErrorCode.unknown;
  }
}
