// GENERATED by tool/generate_api.dart from tool/openapi.json
// (Slopcafe API contract 0.10.0). DO NOT EDIT BY HAND.
// Re-run `dart run tool/generate_api.dart && dart run build_runner build`
// after re-pinning the spec. See GEMINI.md.

// ignore_for_file: invalid_annotation_target

import 'package:freezed_annotation/freezed_annotation.dart';

part 'models.freezed.dart';
part 'models.g.dart';

@freezed
abstract class BackfillResponse with _$BackfillResponse {
  const factory BackfillResponse({
    @JsonKey(name: 'mode') required String mode,
    @JsonKey(name: 'scanned') required int scanned,
    @JsonKey(name: 'embedded') required int embedded,
    @JsonKey(name: 'vectors') required int vectors,
    @JsonKey(name: 'skipped') required int skipped,
    @JsonKey(name: 'next_cursor') String? nextCursor,
  }) = _BackfillResponse;

  factory BackfillResponse.fromJson(Map<String, dynamic> json) =>
      _$BackfillResponseFromJson(json);
}

@freezed
abstract class ClearSlugRedirectResponse with _$ClearSlugRedirectResponse {
  const factory ClearSlugRedirectResponse({
    @JsonKey(name: 'slug') required String slug,
    @JsonKey(name: 'redirect_to') dynamic redirectTo,
  }) = _ClearSlugRedirectResponse;

  factory ClearSlugRedirectResponse.fromJson(Map<String, dynamic> json) =>
      _$ClearSlugRedirectResponseFromJson(json);
}

@freezed
abstract class CreateOAuthClientResponse with _$CreateOAuthClientResponse {
  const factory CreateOAuthClientResponse({
    @JsonKey(name: 'client_id') required String clientId,
    @JsonKey(name: 'client_secret') required String clientSecret,
    @JsonKey(name: 'mcp_url') required String mcpUrl,
    @JsonKey(name: 'agent_id') required String agentId,
    @JsonKey(name: 'agent_name') required String agentName,
    @JsonKey(name: 'note') required String note,
  }) = _CreateOAuthClientResponse;

  factory CreateOAuthClientResponse.fromJson(Map<String, dynamic> json) =>
      _$CreateOAuthClientResponseFromJson(json);
}

@freezed
abstract class CreateUnboundOAuthClientResponse
    with _$CreateUnboundOAuthClientResponse {
  const factory CreateUnboundOAuthClientResponse({
    @JsonKey(name: 'client_id') required String clientId,
    @JsonKey(name: 'client_secret') required String clientSecret,
    @JsonKey(name: 'mcp_url') required String mcpUrl,
    @JsonKey(name: 'note') required String note,
  }) = _CreateUnboundOAuthClientResponse;

  factory CreateUnboundOAuthClientResponse.fromJson(
    Map<String, dynamic> json,
  ) => _$CreateUnboundOAuthClientResponseFromJson(json);
}

@freezed
abstract class DocumentListing with _$DocumentListing {
  const DocumentListing._();
  const factory DocumentListing({
    @JsonKey(name: 'public_id') required String publicId,
    @JsonKey(name: 'created_at') required DateTime createdAt,
    @JsonKey(name: 'created_by_kind') required String createdByKind,
    @JsonKey(name: 'tags') required List<String> tags,
    @JsonKey(name: 'status') required String status,
    @JsonKey(name: 'visibility') required String visibility,
    @JsonKey(name: 'current_ver') int? currentVer,
    @JsonKey(name: 'created_by_id') String? createdById,
    @JsonKey(name: 'created_by_name') String? createdByName,
    @JsonKey(name: 'current_size') int? currentSize,
    @JsonKey(name: 'revoked_at') DateTime? revokedAt,
    @JsonKey(name: 'title') String? title,
    @JsonKey(name: 'description') String? description,
    @JsonKey(name: 'slug') String? slug,
    @JsonKey(name: 'superseded_by') String? supersededBy,
  }) = _DocumentListing;

  bool get isRevoked => revokedAt != null;

  factory DocumentListing.fromJson(Map<String, dynamic> json) =>
      _$DocumentListingFromJson(json);
}

@freezed
abstract class HealthzResponse with _$HealthzResponse {
  const factory HealthzResponse({
    @JsonKey(name: 'ok') required bool ok,
    @JsonKey(name: 'service') required String service,
    @JsonKey(name: 'sanitizer_version') required String sanitizerVersion,
    @JsonKey(name: 'storage_cap_bytes') required int storageCapBytes,
    @JsonKey(name: 'd1') required HealthzResponseD1 d1,
    @JsonKey(name: 'r2') required HealthzResponseR2 r2,
  }) = _HealthzResponse;

  factory HealthzResponse.fromJson(Map<String, dynamic> json) =>
      _$HealthzResponseFromJson(json);
}

@freezed
abstract class HealthzResponseD1 with _$HealthzResponseD1 {
  const factory HealthzResponseD1({
    @JsonKey(name: 'documents') int? documents,
    @JsonKey(name: 'agents') int? agents,
  }) = _HealthzResponseD1;

  factory HealthzResponseD1.fromJson(Map<String, dynamic> json) =>
      _$HealthzResponseD1FromJson(json);
}

@freezed
abstract class HealthzResponseR2 with _$HealthzResponseR2 {
  const factory HealthzResponseR2({
    @JsonKey(name: 'bucket_reachable') required bool bucketReachable,
    @JsonKey(name: 'sample_object_count') required int sampleObjectCount,
  }) = _HealthzResponseR2;

  factory HealthzResponseR2.fromJson(Map<String, dynamic> json) =>
      _$HealthzResponseR2FromJson(json);
}

@freezed
abstract class ListAgentKeysResponse with _$ListAgentKeysResponse {
  const factory ListAgentKeysResponse({
    @JsonKey(name: 'agent_id') required String agentId,
    @JsonKey(name: 'name') required String name,
    @JsonKey(name: 'keys') required List<AgentKey> keys,
    @JsonKey(name: 'next_cursor') String? nextCursor,
  }) = _ListAgentKeysResponse;

  factory ListAgentKeysResponse.fromJson(Map<String, dynamic> json) =>
      _$ListAgentKeysResponseFromJson(json);
}

@freezed
abstract class AgentKey with _$AgentKey {
  const AgentKey._();
  const factory AgentKey({
    @JsonKey(name: 'id') required String id,
    @JsonKey(name: 'key_prefix') required String keyPrefix,
    @JsonKey(name: 'created_at') required DateTime createdAt,
    @JsonKey(name: 'expired') required bool expired,
    @JsonKey(name: 'revoked_at') DateTime? revokedAt,
    @JsonKey(name: 'expires_at') DateTime? expiresAt,
  }) = _AgentKey;

  bool get isRevoked => revokedAt != null;
  bool get isActive => !isRevoked && !expired;

  factory AgentKey.fromJson(Map<String, dynamic> json) =>
      _$AgentKeyFromJson(json);
}

@freezed
abstract class ListAgentsResponse with _$ListAgentsResponse {
  const factory ListAgentsResponse({
    @JsonKey(name: 'agents') required List<AgentListing> agents,
    @JsonKey(name: 'next_cursor') String? nextCursor,
  }) = _ListAgentsResponse;

  factory ListAgentsResponse.fromJson(Map<String, dynamic> json) =>
      _$ListAgentsResponseFromJson(json);
}

@freezed
abstract class AgentListing with _$AgentListing {
  const factory AgentListing({
    @JsonKey(name: 'id') required String id,
    @JsonKey(name: 'name') required String name,
    @JsonKey(name: 'created_at') required DateTime createdAt,
    @JsonKey(name: 'active_keys') required int activeKeys,
    @JsonKey(name: 'total_keys') required int totalKeys,
    @JsonKey(name: 'live_docs') required int liveDocs,
  }) = _AgentListing;

  factory AgentListing.fromJson(Map<String, dynamic> json) =>
      _$AgentListingFromJson(json);
}

@freezed
abstract class ListDocumentsResponse with _$ListDocumentsResponse {
  const factory ListDocumentsResponse({
    @JsonKey(name: 'documents') required List<DocumentListing> documents,
    @JsonKey(name: 'next_cursor') String? nextCursor,
  }) = _ListDocumentsResponse;

  factory ListDocumentsResponse.fromJson(Map<String, dynamic> json) =>
      _$ListDocumentsResponseFromJson(json);
}

@freezed
abstract class MintAgentKeyResponse with _$MintAgentKeyResponse {
  const factory MintAgentKeyResponse({
    @JsonKey(name: 'agent_id') required String agentId,
    @JsonKey(name: 'key_id') required String keyId,
    @JsonKey(name: 'key') required String key,
    @JsonKey(name: 'note') required String note,
  }) = _MintAgentKeyResponse;

  factory MintAgentKeyResponse.fromJson(Map<String, dynamic> json) =>
      _$MintAgentKeyResponseFromJson(json);
}

@freezed
abstract class PackDocument with _$PackDocument {
  const factory PackDocument({
    @JsonKey(name: 'public_id') required String publicId,
    @JsonKey(name: 'created_at') required DateTime createdAt,
    @JsonKey(name: 'created_by_kind') required String createdByKind,
    @JsonKey(name: 'tags') required List<String> tags,
    @JsonKey(name: 'status') required String status,
    @JsonKey(name: 'visibility') required String visibility,
    @JsonKey(name: 'content') required String content,
    @JsonKey(name: 'format') required String format,
    @JsonKey(name: 'converter_v') required String converterV,
    @JsonKey(name: 'version') required int version,
    @JsonKey(name: 'current_ver') int? currentVer,
    @JsonKey(name: 'created_by_id') String? createdById,
    @JsonKey(name: 'created_by_name') String? createdByName,
    @JsonKey(name: 'current_size') int? currentSize,
    @JsonKey(name: 'revoked_at') DateTime? revokedAt,
    @JsonKey(name: 'title') String? title,
    @JsonKey(name: 'description') String? description,
    @JsonKey(name: 'slug') String? slug,
    @JsonKey(name: 'superseded_by') String? supersededBy,
    @JsonKey(name: 'score') double? score,
    @JsonKey(name: 'matched_field') String? matchedField,
    @JsonKey(name: 'snippet') String? snippet,
    @JsonKey(name: 'tier') String? tier,
    @JsonKey(name: 'hint') String? hint,
  }) = _PackDocument;

  factory PackDocument.fromJson(Map<String, dynamic> json) =>
      _$PackDocumentFromJson(json);
}

@freezed
abstract class PackInfo with _$PackInfo {
  const factory PackInfo({
    @JsonKey(name: 'source') required String source,
    @JsonKey(name: 'budget_bytes') required int budgetBytes,
    @JsonKey(name: 'max_documents') required int maxDocuments,
    @JsonKey(name: 'used_bytes') required int usedBytes,
    @JsonKey(name: 'query') String? query,
    @JsonKey(name: 'root') PackRoot? root,
  }) = _PackInfo;

  factory PackInfo.fromJson(Map<String, dynamic> json) =>
      _$PackInfoFromJson(json);
}

@freezed
abstract class PackRoot with _$PackRoot {
  const factory PackRoot({
    @JsonKey(name: 'public_id') required String publicId,
    @JsonKey(name: 'content') required String content,
    @JsonKey(name: 'format') required String format,
    @JsonKey(name: 'slug') String? slug,
    @JsonKey(name: 'title') String? title,
  }) = _PackRoot;

  factory PackRoot.fromJson(Map<String, dynamic> json) =>
      _$PackRootFromJson(json);
}

@freezed
abstract class PackOmitted with _$PackOmitted {
  const factory PackOmitted({
    @JsonKey(name: 'ref') required String ref,
    @JsonKey(name: 'reason') required String reason,
    @JsonKey(name: 'public_id') String? publicId,
    @JsonKey(name: 'title') String? title,
    @JsonKey(name: 'size_bytes') int? sizeBytes,
    @JsonKey(name: 'superseded_by') String? supersededBy,
    @JsonKey(name: 'hint') String? hint,
  }) = _PackOmitted;

  factory PackOmitted.fromJson(Map<String, dynamic> json) =>
      _$PackOmittedFromJson(json);
}

@freezed
abstract class PackResponse with _$PackResponse {
  const factory PackResponse({
    @JsonKey(name: 'pack') required PackInfo pack,
    @JsonKey(name: 'documents') required List<PackDocument> documents,
    @JsonKey(name: 'omitted') required List<PackOmitted> omitted,
  }) = _PackResponse;

  factory PackResponse.fromJson(Map<String, dynamic> json) =>
      _$PackResponseFromJson(json);
}

@freezed
abstract class ReadSourceResponse with _$ReadSourceResponse {
  const factory ReadSourceResponse({
    @JsonKey(name: 'source') required String source,
    @JsonKey(name: 'source_format') required String sourceFormat,
    @JsonKey(name: 'version_no') required int versionNo,
    @JsonKey(name: 'sanitizer_v') required String sanitizerV,
    @JsonKey(name: 'stripped') required List<String> stripped,
    @JsonKey(name: 'will_not_render') required List<String> willNotRender,
    @JsonKey(name: 'tags') required List<String> tags,
    @JsonKey(name: 'status') required String status,
    @JsonKey(name: 'unsanitized') required bool unsanitized,
    @JsonKey(name: 'title') String? title,
    @JsonKey(name: 'description') String? description,
    @JsonKey(name: 'slug') String? slug,
    @JsonKey(name: 'superseded_by') String? supersededBy,
  }) = _ReadSourceResponse;

  factory ReadSourceResponse.fromJson(Map<String, dynamic> json) =>
      _$ReadSourceResponseFromJson(json);
}

@freezed
abstract class RedirectTarget with _$RedirectTarget {
  const factory RedirectTarget({
    @JsonKey(name: 'public_id') required String publicId,
    @JsonKey(name: 'slug') String? slug,
    @JsonKey(name: 'title') String? title,
  }) = _RedirectTarget;

  factory RedirectTarget.fromJson(Map<String, dynamic> json) =>
      _$RedirectTargetFromJson(json);
}

@freezed
abstract class ReleaseSlugTombstoneResponse
    with _$ReleaseSlugTombstoneResponse {
  const factory ReleaseSlugTombstoneResponse({
    @JsonKey(name: 'released') required bool released,
    @JsonKey(name: 'slug') required String slug,
  }) = _ReleaseSlugTombstoneResponse;

  factory ReleaseSlugTombstoneResponse.fromJson(Map<String, dynamic> json) =>
      _$ReleaseSlugTombstoneResponseFromJson(json);
}

@freezed
abstract class RevokeAgentResponse with _$RevokeAgentResponse {
  const factory RevokeAgentResponse({
    @JsonKey(name: 'revoked') required bool revoked,
    @JsonKey(name: 'agent_id') required String agentId,
    @JsonKey(name: 'keys_revoked') required int keysRevoked,
    @JsonKey(name: 'oauth_clients_deleted') required int oauthClientsDeleted,
  }) = _RevokeAgentResponse;

  factory RevokeAgentResponse.fromJson(Map<String, dynamic> json) =>
      _$RevokeAgentResponseFromJson(json);
}

@freezed
abstract class RevokeKeyResponse with _$RevokeKeyResponse {
  const factory RevokeKeyResponse({
    @JsonKey(name: 'revoked') required bool revoked,
    @JsonKey(name: 'key_id') required String keyId,
    @JsonKey(name: 'agent_id') required String agentId,
    @JsonKey(name: 'key_prefix') required String keyPrefix,
  }) = _RevokeKeyResponse;

  factory RevokeKeyResponse.fromJson(Map<String, dynamic> json) =>
      _$RevokeKeyResponseFromJson(json);
}

@freezed
abstract class RevokeResponse with _$RevokeResponse {
  const factory RevokeResponse({
    @JsonKey(name: 'revoked') required bool revoked,
    @JsonKey(name: 'public_id') required String publicId,
    @JsonKey(name: 'r2_objects_purged') required int r2ObjectsPurged,
  }) = _RevokeResponse;

  factory RevokeResponse.fromJson(Map<String, dynamic> json) =>
      _$RevokeResponseFromJson(json);
}

@freezed
abstract class SearchDocumentsResponse with _$SearchDocumentsResponse {
  const factory SearchDocumentsResponse({
    @JsonKey(name: 'documents') required List<SearchHit> documents,
  }) = _SearchDocumentsResponse;

  factory SearchDocumentsResponse.fromJson(Map<String, dynamic> json) =>
      _$SearchDocumentsResponseFromJson(json);
}

@freezed
abstract class SearchHit with _$SearchHit {
  const SearchHit._();
  const factory SearchHit({
    @JsonKey(name: 'public_id') required String publicId,
    @JsonKey(name: 'created_at') required DateTime createdAt,
    @JsonKey(name: 'created_by_kind') required String createdByKind,
    @JsonKey(name: 'tags') required List<String> tags,
    @JsonKey(name: 'status') required String status,
    @JsonKey(name: 'visibility') required String visibility,
    @JsonKey(name: 'score') required double score,
    @JsonKey(name: 'matched_field') required String matchedField,
    @JsonKey(name: 'snippet') required String snippet,
    @JsonKey(name: 'current_ver') int? currentVer,
    @JsonKey(name: 'created_by_id') String? createdById,
    @JsonKey(name: 'created_by_name') String? createdByName,
    @JsonKey(name: 'current_size') int? currentSize,
    @JsonKey(name: 'revoked_at') DateTime? revokedAt,
    @JsonKey(name: 'title') String? title,
    @JsonKey(name: 'description') String? description,
    @JsonKey(name: 'slug') String? slug,
    @JsonKey(name: 'superseded_by') String? supersededBy,
  }) = _SearchHit;

  /// The listing slice of this hit (the fields shared with DocumentListing).
  DocumentListing get document => DocumentListing(
    publicId: publicId,
    currentVer: currentVer,
    createdAt: createdAt,
    createdById: createdById,
    createdByName: createdByName,
    createdByKind: createdByKind,
    currentSize: currentSize,
    revokedAt: revokedAt,
    title: title,
    description: description,
    tags: tags,
    slug: slug,
    status: status,
    supersededBy: supersededBy,
    visibility: visibility,
  );

  /// Build a hit from a listing — used by the offline local-search fallback.
  factory SearchHit.fromDocument(
    DocumentListing doc, {
    required double score,
    required String matchedField,
    required String snippet,
  }) => SearchHit(
    publicId: doc.publicId,
    currentVer: doc.currentVer,
    createdAt: doc.createdAt,
    createdById: doc.createdById,
    createdByName: doc.createdByName,
    createdByKind: doc.createdByKind,
    currentSize: doc.currentSize,
    revokedAt: doc.revokedAt,
    title: doc.title,
    description: doc.description,
    tags: doc.tags,
    slug: doc.slug,
    status: doc.status,
    supersededBy: doc.supersededBy,
    visibility: doc.visibility,
    score: score,
    matchedField: matchedField,
    snippet: snippet,
  );

  factory SearchHit.fromJson(Map<String, dynamic> json) =>
      _$SearchHitFromJson(json);
}

@freezed
abstract class SetDocumentSlugResponse with _$SetDocumentSlugResponse {
  const factory SetDocumentSlugResponse({
    @JsonKey(name: 'public_id') required String publicId,
    @JsonKey(name: 'redirected') required bool redirected,
    @JsonKey(name: 'slug') String? slug,
    @JsonKey(name: 'retired') String? retired,
  }) = _SetDocumentSlugResponse;

  factory SetDocumentSlugResponse.fromJson(Map<String, dynamic> json) =>
      _$SetDocumentSlugResponseFromJson(json);
}

@freezed
abstract class SetDocumentStatusResponse with _$SetDocumentStatusResponse {
  const factory SetDocumentStatusResponse({
    @JsonKey(name: 'public_id') required String publicId,
    @JsonKey(name: 'status') required String status,
    @JsonKey(name: 'superseded_by') String? supersededBy,
  }) = _SetDocumentStatusResponse;

  factory SetDocumentStatusResponse.fromJson(Map<String, dynamic> json) =>
      _$SetDocumentStatusResponseFromJson(json);
}

@freezed
abstract class SetDocumentTagsResponse with _$SetDocumentTagsResponse {
  const factory SetDocumentTagsResponse({
    @JsonKey(name: 'public_id') required String publicId,
    @JsonKey(name: 'tags') required List<String> tags,
  }) = _SetDocumentTagsResponse;

  factory SetDocumentTagsResponse.fromJson(Map<String, dynamic> json) =>
      _$SetDocumentTagsResponseFromJson(json);
}

@freezed
abstract class SetDocumentVisibilityResponse
    with _$SetDocumentVisibilityResponse {
  const factory SetDocumentVisibilityResponse({
    @JsonKey(name: 'public_id') required String publicId,
    @JsonKey(name: 'visibility') required String visibility,
  }) = _SetDocumentVisibilityResponse;

  factory SetDocumentVisibilityResponse.fromJson(Map<String, dynamic> json) =>
      _$SetDocumentVisibilityResponseFromJson(json);
}

@freezed
abstract class SetSlugRedirectResponse with _$SetSlugRedirectResponse {
  const factory SetSlugRedirectResponse({
    @JsonKey(name: 'slug') required String slug,
    @JsonKey(name: 'redirect_to') required String redirectTo,
    @JsonKey(name: 'target_slug') String? targetSlug,
    @JsonKey(name: 'target_title') String? targetTitle,
  }) = _SetSlugRedirectResponse;

  factory SetSlugRedirectResponse.fromJson(Map<String, dynamic> json) =>
      _$SetSlugRedirectResponseFromJson(json);
}

@freezed
abstract class WriteResponse with _$WriteResponse {
  const factory WriteResponse({
    @JsonKey(name: 'public_id') required String publicId,
    @JsonKey(name: 'url') required String url,
    @JsonKey(name: 'version') required int version,
    @JsonKey(name: 'size_bytes') required int sizeBytes,
    @JsonKey(name: 'sanitizer_v') required String sanitizerV,
    @JsonKey(name: 'modified') required bool modified,
    @JsonKey(name: 'stripped') required List<String> stripped,
    @JsonKey(name: 'will_not_render') required List<String> willNotRender,
    @JsonKey(name: 'tags') required List<String> tags,
    @JsonKey(name: 'title') String? title,
    @JsonKey(name: 'description') String? description,
    @JsonKey(name: 'slug') String? slug,
  }) = _WriteResponse;

  factory WriteResponse.fromJson(Map<String, dynamic> json) =>
      _$WriteResponseFromJson(json);
}
